"""Remove map-related fields

Revision ID: 19aafa31e0d9
Revises: cefbc921568c
Create Date: 2026-03-16 01:09:45.325420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19aafa31e0d9'
down_revision = 'cefbc921568c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amenity_resource', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_amenity_resource_resource_type_id_amenity_resource_type'), 'amenity_resource_type', ['resource_type_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_amenity_resource_unit_type_id_unit_type'), 'unit_type', ['unit_type_id'], ['id'])

    with op.batch_alter_table('amenity_resource_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amenity_resource_type_name'))

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('map_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_url', sa.TEXT(), nullable=True))

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('amenity_resource_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amenity_resource_type_name'), ['name'], unique=False)

    with op.batch_alter_table('amenity_resource', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
