"""Add email confirmation and incoming mail settings

Revision ID: 393075827ce4
Revises: ed0b716f9a50
Create Date: 2026-03-11 21:25:36.611191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393075827ce4'
down_revision = 'ed0b716f9a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
