"""Add cancel_reason to booking

Revision ID: 64fede2036c0
Revises: ff602f451674
Create Date: 2026-03-11 02:43:06.730094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fede2036c0'
down_revision = 'ff602f451674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('characteristic_type', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'unit_type', ['unit_type_id'], ['id'])

    with op.batch_alter_table('option_type', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'unit_type', ['unit_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('characteristic_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('cancel_reason')

    # ### end Alembic commands ###
