"""change local_video_url to local_video_urls Text

Revision ID: 6b58699d494c
Revises: 92fdbba65839
Create Date: 2026-03-05 18:42:52.958061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b58699d494c'
down_revision = '92fdbba65839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_video_urls', sa.Text(), nullable=True))
        batch_op.drop_column('local_video_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_video_url', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('local_video_urls')

    # ### end Alembic commands ###
