"""Add base_guests and extra_guest_price to Property

Revision ID: 74f77268b370
Revises: f104eaf1be9e
Create Date: 2026-03-15 22:52:20.253270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f77268b370'
down_revision = 'f104eaf1be9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_guests', sa.Integer(), nullable=False, server_default='2'))
        batch_op.add_column(sa.Column('extra_guest_price', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('extra_guest_price')
        batch_op.drop_column('base_guests')

    # ### end Alembic commands ###
