"""Add telegram_chat_id to Property

Revision ID: 884d5896d091
Revises: 75ec7a77e596
Create Date: 2026-03-07 00:33:38.378787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884d5896d091'
down_revision = '75ec7a77e596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
