"""add local_video_url to property

Revision ID: 92fdbba65839
Revises: 16954b916c40
Create Date: 2026-03-05 18:37:15.416170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fdbba65839'
down_revision = '16954b916c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('property', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('local_video_url', sa.String(length=300), nullable=True))
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('property', schema=None) as batch_op:
    #     batch_op.drop_column('local_video_url')
    pass

    # ### end Alembic commands ###
