"""Initial migration

Revision ID: 97501b8c1cc7
Revises: 
Create Date: 2026-03-05 18:19:12.988713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97501b8c1cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text("'2026-03-05 14:55:44'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text("'2026-03-05 14:55:44'"))

    # ### end Alembic commands ###
