"""Add seo_keywords and min_rent_days to Property

Revision ID: cefbc921568c
Revises: 74f77268b370
Create Date: 2026-03-15 23:05:57.291960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cefbc921568c'
down_revision = '74f77268b370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_rent_days', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('seo_keywords', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('seo_keywords')
        batch_op.drop_column('min_rent_days')

    # ### end Alembic commands ###
