"""Add working_hours to SiteSettings

Revision ID: f104eaf1be9e
Revises: c8e2a7f4b0d1
Create Date: 2026-03-15 13:24:50.895148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f104eaf1be9e'
down_revision = 'c8e2a7f4b0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_hours', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('working_hours')

    with op.batch_alter_table('amenity_resource_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amenity_resource_type_name'), ['name'], unique=False)

    with op.batch_alter_table('amenity_resource', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
