"""Add booking devices and passkeys

Revision ID: ff602f451674
Revises: 884d5896d091
Create Date: 2026-03-10 23:10:42.134762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff602f451674'
down_revision = '884d5896d091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
