"""Add booking devices and passkeys

Revision ID: ff602f451674
Revises: 884d5896d091
Create Date: 2026-03-10 23:10:42.134762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff602f451674'
down_revision = '884d5896d091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=200), nullable=False),
    sa.Column('device_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('booking_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_device_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_device_device_token_hash'), ['device_token_hash'], unique=False)

    op.create_table('booking_passkey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=300), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.String(length=200), nullable=True),
    sa.Column('aaguid', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_passkey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_passkey_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_passkey_credential_id'), ['credential_id'], unique=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_booking_booking_token'), ['booking_token'], unique=True)

    with op.batch_alter_table('characteristic_type', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_characteristic_type_unit_type', 'unit_type', ['unit_type_id'], ['id'])

    with op.batch_alter_table('option_type', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_option_type_unit_type', 'unit_type', ['unit_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('characteristic_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_booking_token'))
        batch_op.drop_column('booking_token')

    with op.batch_alter_table('booking_passkey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_passkey_credential_id'))
        batch_op.drop_index(batch_op.f('ix_booking_passkey_booking_id'))

    op.drop_table('booking_passkey')
    with op.batch_alter_table('booking_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_device_device_token_hash'))
        batch_op.drop_index(batch_op.f('ix_booking_device_booking_id'))

    op.drop_table('booking_device')
    # ### end Alembic commands ###
